# Creates the root .env that docker-compose needs, with freshly generated JWT
# secrets. Run automatically by start.bat when no .env is present; safe to run by
# hand. Never overwrites an existing file.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $root '.env'

if (Test-Path $envPath) {
    Write-Host "  .env already exists - leaving it untouched."
    exit 0
}

function New-Secret {
    # 48 bytes of cryptographic randomness, URL-safe base64 (matches
    # Python's secrets.token_urlsafe(48) used on the backend).
    $bytes = New-Object byte[] 48
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

$lines = @(
    '# Generated by scripts/new-env.ps1 - do not commit this file.',
    '# docker-compose reads these when starting the app container.',
    '',
    "JWT_SECRET_KEY=$(New-Secret)",
    "JWT_REFRESH_SECRET_KEY=$(New-Secret)"
)

Set-Content -Path $envPath -Value $lines -Encoding utf8
Write-Host "  Created .env with two freshly generated secrets."
